// <auto-generated />
namespace Todo.Site.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201301192046577_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
